# Generated by Django 4.2.9 on 2024-02-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0003_auto_20240131_1448"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
